### ISSUE TITLE
Run provided checkpoint in Get3D KeyError: 'G'

### ISSUE THREAD

**Issue by yiwenjinbf** [studio-YAIVERSE/Backend#15]
Hi,
I am trying to run the provided checkpoint, car_taxicar.pt, and I run into this error 
Traceback (most recent call last):
  File "train_3d.py", line 337, in <module>
    main()  # pylint: disable=no-value-for-parameter
  File "/home/yiwen/anaconda3/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/yiwen/anaconda3/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/yiwen/anaconda3/envs/get3d/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yiwen/anaconda3/envs/get3d/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "train_3d.py", line 331, in main
    launch_training(c=c, desc=desc, outdir=opts.outdir, dry_run=opts.dry_run)
  File "train_3d.py", line 103, in launch_training
    subprocess_fn(rank=0, c=c, temp_dir=temp_dir)
  File "train_3d.py", line 46, in subprocess_fn
    inference_3d.inference(rank=rank, **c)
  File "/home/yiwen/GET3D/training/inference_3d.py", line 77, in inference
    G.load_state_dict(model_state_dict['G'], strict=True)
KeyError: 'G'
And when I run the pretained model in GET3D, for example shapenet_chair.pt, it works

**Comment by yiwenjinbf** [comment]
nvm fixed, I got my banana car
